version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: app
    image: app
    environment:
      MYSQL_DSN: 'root:secret@tcp(localhost:3306)/dev?charset=utf8&parseTime=True&loc=Local'
    network_mode: "host"
    depends_on:
      - mysql
