version: "3"

services:
  node:
    image: node:lts
    container_name: node
    volumes:
      - /code:/code
    tty: true
    working_dir: /code
    environment:
      TZ: Asia/Shanghai

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/data:/data
    # 设置登录密码
    command: redis-server --requirepass 123456

  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    volumes:
      - /code/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:management # 此版本才带有管理界面
    container_name: rabbitmq
    ports:
      - "5672:5672" # mq本身
      - "15672:15672" # 管理界面
    environment:
      TZ: Asia/Shanghai

  es:
    image: elasticsearch:7.14.2
    container_name: es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m # 限制使用内存,初始会直接使用16G以上内存
      xpack.security.enabled: false # 不启动安全防护,方便使用 curl 测试
  
  postgres:
    image:  postgres:latest
    container_name: post
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --auth=md5 # 使用不支持 scram-sha-256 登录时设置

  click:
    image: clickhouse/clickhouse-server
    container_name: click
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: normal
      CLICKHOUSE_PASSWORD: secret
    tty: true
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  cuda:
    image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04
    container_name: cuda
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]