version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m # memory limit
  kibana:
    image: kibana:8.8.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
  # logstash:
  #   image: logstash:8.8.1
  #   container_name: logstash
  #   ports:
  #     - "5602:5602"
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:8.8.1
  #   container_name: filebeat
  #   volumes:
  #     - /log:/log
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.8.1
    container_name: metricbeat
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    network_mode: host
    depends_on:
      - elasticsearch
      - kibana
