version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipelines:/usr/share/logstash/pipelines:ro
    depends_on:
      - elasticsearch
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION}
    container_name: metricbeat
    user: root
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      CA_FINGERPRINT: ${CA_FINGERPRINT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - elasticsearch
      - kibana
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    container_name: filebeat
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      CA_FINGERPRINT: ${CA_FINGERPRINT}
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:${ELASTIC_VERSION}
    container_name: apm-server
    hostname: apm-server
    ports:
      - 8200:8200
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      CA_FINGERPRINT: ${CA_FINGERPRINT}
    command: --strict.perms=false -e
    depends_on:
      - elasticsearch
      - kibana
