filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
## ref https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html
filebeat.inputs:
- type: filestream
  id: filestream-example-id
  paths:
    - /log/*.log

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

#  default index is ".ds-filebeat-%{[agent.version]}-%{+yyyy.MM.dd}-%{index_num}", for example, ".ds-filebeat-8.11.3-2024.01.18-000001"
output.elasticsearch:
  hosts: [ https://elasticsearch:9200 ]
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    ca_trusted_fingerprint: ${CA_FINGERPRINT}