metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ['https://elasticsearch:9200']
  username: 'elastic'
  password: '${ELASTICSEARCH_PASSWORD}'
  ssl:
    enabled: true
    ca_trusted_fingerprint: '${CA_FINGERPRINT}'
setup.kibana:
    host: "kibana:5601"