version: "2"
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    container_name: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode1:
    image: apache/hadoop:3
    container_name: datanode1
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
  datanode2:
    image: apache/hadoop:3
    container_name: datanode2
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
  datanode3:
    image: apache/hadoop:3
    container_name: datanode3
    command: ["hdfs", "datanode"]
    env_file:
      - ./config    
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
       - 8088:8088
    env_file:
      - ./config
  nodemanager:
    image: apache/hadoop:3
    container_name: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config