basePath: /api/v1
definitions:
  entities.User:
    properties:
      create_at:
        type: string
      deleted:
        type: boolean
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      update_at:
        type: string
    type: object
  user.RegisterDto:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  utils.HttpDeleteResponse:
    properties:
      deleteItems:
        example: 1
        type: integer
    type: object
  utils.HttpErorr:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: user register
      parameters:
      - description: User required name && email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RegisterDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
      summary: register
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: delete user
      parameters:
      - description: User ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.HttpDeleteResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HttpErorr'
      summary: deactivate
      tags:
      - users
    get:
      consumes:
      - application/json
      description: get user
      parameters:
      - description: User ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HttpErorr'
      summary: findUser
      tags:
      - users
swagger: "2.0"
