version: "3"

services:
  influx:
    image: influxdb:latest
    container_name: influx
    volumes:
      - ./influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt
      - ./influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: rooot
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password ## least 8 char
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: cwXmMd95WtP8q_RQWov_bUlKi8cXSRmCxrcgGV6SERLIoYv8gqa28hJ6jgukauqMhGJwNAGek9fuWlBPSU2QBw==
      INFLUXD_TLS_CERT: /etc/ssl/influxdb-selfsigned.crt
      INFLUXD_TLS_KEY: /etc/ssl/influxdb-selfsigned.key
    ports: 
      - 8086:8086