version: "3"

services:
  mysql-ssl:
    image: mysql:8.0
    container_name: mysql-ssl
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      auto_generate_certs: true